-- Brochure Studio.
--
-- Brochures are a *presentation* of the trip catalogue, never a second copy of
-- it. A live brochure holds only references — which trips, in which order, with
-- which editorial copy — and reads titles, imagery and itineraries from the
-- trips tables at render time. A snapshot brochure additionally stores a frozen
-- copy in snapshot_data, so a proposal sent to a school in March still reads the
-- same in September.
--
-- The trips table remains the source of truth in both cases.

create table if not exists public.brochures (
  id                bigint generated by default as identity primary key,
  slug              text not null unique,
  title             text not null,
  subtitle          text,

  -- master | subject | destination | custom
  kind              text not null default 'custom',
  -- draft | published | archived
  status            text not null default 'draft',
  -- public | unlisted  (unlisted is reachable by link but never listed or indexed)
  visibility        text not null default 'unlisted',
  -- live | snapshot
  publishing_mode   text not null default 'live',
  -- inspiration | standard | detailed — drives how much copy each trip gets
  detail_level      text not null default 'standard',

  -- Bespoke school proposals
  client_name       text,
  client_logo       text,

  cover_image       text,
  intro_text        text,
  closing_text      text,

  -- Selection. trip_ids carries the running order; the arrays record what the
  -- admin asked for, so a subject brochure can be refreshed as trips are added.
  trip_ids          jsonb not null default '[]',
  subject_ids       jsonb not null default '[]',
  country_ids       jsonb not null default '[]',

  -- { showPricing, showSafety, showApp, showItinerary, showTerms, coverTheme, showClientLogo, … }
  design            jsonb not null default '{}',

  -- Optional gate for bespoke proposals. Hash only — never the password itself.
  password_hash     text,

  seo_title         text,
  seo_description   text,

  -- Frozen render for publishing_mode = 'snapshot'
  snapshot_data     jsonb,

  published_at      timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

comment on column public.brochures.snapshot_data is
  'Frozen page content for snapshot brochures. Null for live brochures, which always read from trips.';

-- Pages are modular blocks so the structure is not hard-coded: reordering,
-- hiding and adding editorial pages is data, not code.
create table if not exists public.brochure_pages (
  id             bigint generated by default as identity primary key,
  brochure_id    bigint not null references public.brochures(id) on delete cascade,

  -- cover | brandIntroduction | textEditorial | subjectDivider | destinationDivider |
  -- tripHero | tripOverview | tripHighlights | tripItinerary | tripGallery |
  -- safety | howItWorks | appFeature | callToAction | contact | backCover
  page_type      text not null,
  sort_order     integer not null default 0,

  -- Which record this page presents, where relevant.
  trip_id        bigint references public.trips(id) on delete cascade,
  subject_id     bigint references public.subjects(id) on delete set null,
  country_id     bigint references public.countries(id) on delete set null,

  -- a | b | c | d — editorial compositions, so the book has rhythm
  layout_variant text not null default 'a',

  -- Editorial copy for this page: { headline, subheadline, intro, highlights[], … }
  -- Written by the AI composer from trip data, then editable by hand.
  content        jsonb not null default '{}',
  background_image text,
  settings       jsonb not null default '{}',

  hidden         boolean not null default false,

  -- ai | reviewed | approved — quality control on generated copy
  copy_status    text not null default 'ai',

  created_at     timestamptz not null default now()
);

create index if not exists brochure_pages_brochure_idx
  on public.brochure_pages (brochure_id, sort_order);
create index if not exists brochures_slug_idx on public.brochures (slug);

-- Privacy-light engagement events. No cookies, no identifiers: one row per
-- meaningful action, enough to tell which trips a school lingered on.
create table if not exists public.brochure_events (
  id           bigint generated by default as identity primary key,
  brochure_id  bigint not null references public.brochures(id) on delete cascade,
  -- view | page | cta | share | trip_click
  event        text not null,
  page_index   integer,
  trip_id      bigint references public.trips(id) on delete set null,
  -- Random per visit, kept only to count sessions. Not a user identifier.
  session_key  text,
  created_at   timestamptz not null default now()
);

create index if not exists brochure_events_brochure_idx
  on public.brochure_events (brochure_id, created_at desc);

/* ─────────────────────────────── security ─────────────────────────────── */

alter table public.brochures      enable row level security;
alter table public.brochure_pages enable row level security;
alter table public.brochure_events enable row level security;

-- Admins manage everything. The public site reads brochures server-side with
-- the service role, which lets password and visibility checks happen before a
-- single byte of an unlisted brochure is sent.
create policy "admin manage brochures" on public.brochures
  for all using (public.is_admin()) with check (public.is_admin());

create policy "admin manage brochure pages" on public.brochure_pages
  for all using (public.is_admin()) with check (public.is_admin());

create policy "admin read brochure events" on public.brochure_events
  for select using (public.is_admin());

-- Published, public brochures are readable by anyone, so the flipbook can be
-- statically rendered. Unlisted and draft brochures never match this.
create policy "public read published brochures" on public.brochures
  for select using (status = 'published' and visibility = 'public');

create policy "public read published brochure pages" on public.brochure_pages
  for select using (
    exists (
      select 1 from public.brochures b
      where b.id = brochure_pages.brochure_id
        and b.status = 'published'
        and b.visibility = 'public'
    )
  );

-- Anyone may record an event against a published brochure; nobody may read them
-- back without admin rights.
create policy "public insert brochure events" on public.brochure_events
  for insert with check (
    exists (
      select 1 from public.brochures b
      where b.id = brochure_events.brochure_id and b.status = 'published'
    )
  );
